export const columns=[
    {
        field:"id",
        headerName:"PId",
        width:80,
        type:"number",
        headerAlign:"center",
        align:"center"
    },
     {
        field:"pName",
        headerName:"ProductName",
        flex:1,
        type:"string",
        headerAlign:"center",
        align:"center"
    },
     {
        field:"price",
        headerName:"Product Price",
        flex:1,
        type:"number",
        headerAlign:"center",
        align:"center"
    },
      {
        field:"available",
        headerName:"Available",
        flex:1,
        type:"boolean",
        headerAlign:"center",
        align:"center"
    },
];

export const rows=[
    {
        id:1,
        pName:"Tv",
        price:40000,
        available:true
    },
     {
        id:2,
        pName:"Fridge",
        price:20000,
        available:true
    },
     {
        id:3,
        pName:"Chair",
        price:400,
        available:false
    },
     {
        id:4,
        pName:"Ac",
        price:60000,
        available:true
    },
     {
        id:5,
        pName:"Water Bottle",
        price:200,
        available:false
    },
];